using System.Collections.Frozen;

namespace BrasilCompete.Worker.Normalization;

/// <summary>
/// Nomes em português das seleções, pelo código de três letras usado nas fontes esportivas (FIFA/COI).
/// Um código desconhecido aparece como está.
/// </summary>
public static class CountryNames
{
    private static readonly FrozenDictionary<string, string> ByCode = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["ALB"] = "Albânia",
        ["ALG"] = "Argélia",
        ["ANG"] = "Angola",
        ["ARG"] = "Argentina",
        ["ARM"] = "Armênia",
        ["AUS"] = "Austrália",
        ["AUT"] = "Áustria",
        ["AZE"] = "Azerbaijão",
        ["BEL"] = "Bélgica",
        ["BFA"] = "Burkina Faso",
        ["BHR"] = "Bahrein",
        ["BIH"] = "Bósnia e Herzegovina",
        ["BLR"] = "Belarus",
        ["BOL"] = "Bolívia",
        ["BRA"] = "Brasil",
        ["BUL"] = "Bulgária",
        ["CAN"] = "Canadá",
        ["CGO"] = "Congo",
        ["CHI"] = "Chile",
        ["CHN"] = "China",
        ["CIV"] = "Costa do Marfim",
        ["CMR"] = "Camarões",
        ["COD"] = "RD Congo",
        ["COL"] = "Colômbia",
        ["CPV"] = "Cabo Verde",
        ["CRC"] = "Costa Rica",
        ["CRO"] = "Croácia",
        ["CUB"] = "Cuba",
        ["CUW"] = "Curaçao",
        ["CYP"] = "Chipre",
        ["CZE"] = "Tchéquia",
        ["DEN"] = "Dinamarca",
        ["DOM"] = "República Dominicana",
        ["ECU"] = "Equador",
        ["EGY"] = "Egito",
        ["ENG"] = "Inglaterra",
        ["ESP"] = "Espanha",
        ["EST"] = "Estônia",
        ["FIN"] = "Finlândia",
        ["FRA"] = "França",
        ["GAB"] = "Gabão",
        ["GEO"] = "Geórgia",
        ["GER"] = "Alemanha",
        ["GHA"] = "Gana",
        ["GRE"] = "Grécia",
        ["GUA"] = "Guatemala",
        ["GUI"] = "Guiné",
        ["HAI"] = "Haiti",
        ["HKG"] = "Hong Kong",
        ["HON"] = "Honduras",
        ["HUN"] = "Hungria",
        ["IDN"] = "Indonésia",
        ["IND"] = "Índia",
        ["IRL"] = "Irlanda",
        ["IRN"] = "Irã",
        ["IRQ"] = "Iraque",
        ["ISL"] = "Islândia",
        ["ISR"] = "Israel",
        ["ITA"] = "Itália",
        ["JAM"] = "Jamaica",
        ["JOR"] = "Jordânia",
        ["JPN"] = "Japão",
        ["KAZ"] = "Cazaquistão",
        ["KEN"] = "Quênia",
        ["KOR"] = "Coreia do Sul",
        ["KSA"] = "Arábia Saudita",
        ["KUW"] = "Kuwait",
        ["LBY"] = "Líbia",
        ["LTU"] = "Lituânia",
        ["LUX"] = "Luxemburgo",
        ["LVA"] = "Letônia",
        ["MAR"] = "Marrocos",
        ["MAS"] = "Malásia",
        ["MEX"] = "México",
        ["MKD"] = "Macedônia do Norte",
        ["MLI"] = "Mali",
        ["MNE"] = "Montenegro",
        ["NCA"] = "Nicarágua",
        ["NED"] = "Holanda",
        ["NGA"] = "Nigéria",
        ["NIR"] = "Irlanda do Norte",
        ["NOR"] = "Noruega",
        ["NZL"] = "Nova Zelândia",
        ["OMA"] = "Omã",
        ["PAN"] = "Panamá",
        ["PAR"] = "Paraguai",
        ["PER"] = "Peru",
        ["PHI"] = "Filipinas",
        ["POL"] = "Polônia",
        ["POR"] = "Portugal",
        ["PRK"] = "Coreia do Norte",
        ["QAT"] = "Catar",
        ["ROU"] = "Romênia",
        ["RSA"] = "África do Sul",
        ["RUS"] = "Rússia",
        ["SCO"] = "Escócia",
        ["SEN"] = "Senegal",
        ["SLV"] = "El Salvador",
        ["SRB"] = "Sérvia",
        ["SUI"] = "Suíça",
        ["SUR"] = "Suriname",
        ["SVK"] = "Eslováquia",
        ["SVN"] = "Eslovênia",
        ["SWE"] = "Suécia",
        ["SYR"] = "Síria",
        ["THA"] = "Tailândia",
        ["TRI"] = "Trinidad e Tobago",
        ["TUN"] = "Tunísia",
        ["TUR"] = "Turquia",
        ["UAE"] = "Emirados Árabes Unidos",
        ["UKR"] = "Ucrânia",
        ["URU"] = "Uruguai",
        ["USA"] = "Estados Unidos",
        ["UZB"] = "Uzbequistão",
        ["VEN"] = "Venezuela",
        ["VIE"] = "Vietnã",
        ["WAL"] = "País de Gales",
        ["ZAM"] = "Zâmbia",
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    public static string For(string code) => ByCode.GetValueOrDefault(code.Trim()) ?? code.Trim().ToUpperInvariant();
}
